[package]
name = "ping-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icmp-socket = "0.2.0"
dns-lookup = "1.0.8"